### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by omazapa** [colav-playground/Yuku#13]
Traceback (most recent call last):
  File "/usr/local/bin/yuku_run", line 47, in <module>
    yuku.download_cvlac(args.download_cvlac)
  File "/usr/local/lib/python3.9/dist-packages/yuku/Yuku.py", line 152, in download_cvlac
    if self.cvlav_private_profile(soup):
  File "/usr/local/lib/python3.9/dist-packages/yuku/Yuku.py", line 45, in cvlav_private_profile
    if text_private == blockquotes[1].text:
IndexError: list index out of range

**Comment by omazapa** [comment]
closed via #14
